---
kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/yuxing-lee/cicd-test/apache
    auto_tag: true
    auto_tag_suffix: apache
    username: yuxing-lee
    password:
      from_secret: GITHUB_TOKEN
