---
kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/yuxing-lee/cicd-test/backend
    tags: ["${DRONE_COMMIT_SHA:0:7}", "latest"]
    dockerfile: ./backend/Dockerfile
    username: yuxing-lee
    password:
      from_secret: GITHUB_TOKEN
  when:
    event:
    - tag
trigger: 
  branch: 
  - master
  - develop
  - feature/*
  event:
  - push
  - tag