---
kind: pipeline
type: docker
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/yuxing-lee/cicd-test/backend
    tags: ["${DRONE_COMMIT_SHA:0:7}", "latest"]
    dockerfile: ./backend/Dockerfile
    username: yuxing-lee
    password:
      from_secret: GITHUB_TOKEN
  when:
    event:
    - tag
- name: notification
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEBHOOK
    channel:
      from_secret: SLACK_CHANNEL
    username: drone
    template: >
      {{#success build.status}}
        Build {{build.number}} succeeded for {{repo.owner}}/{{repo.name}}.
      {{else}}
        Build {{build.number}} failed for {{repo.owner}}/{{repo.name}}.
      {{/success}}
  when:
    status:
    - success
    - failure
trigger:
  branch:
  - master
  - develop
  - feature/*
  event:
  - push
  - tag
