version: '2'

services:
  drone-server:
    image: drone/drone:1
    container_name: drone-server
    ports:
      - 80:80
    volumes:
      - /var/lib/drone:/var/lib/drone/
      - /data:/data
    restart: always
    environment:
      - DRONE_SERVER_HOST="{YOUR_MACHINE_HOST}"
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=db242daf100b137d40f7f40f82168b7b
      - DRONE_GITHUB_CLIENT_ID="{CLIENT_ID}"
      - DRONE_GITHUB_CLIENT_SECRET="{CLIENT_SECRET}"

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=db242daf100b137d40f7f40f82168b7b
      - DRONE_RUNNER_CAPACITY=2